import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Tooltip from '@mui/material/Tooltip'
export default function Home() {
    useEffect(() => {
        if (window !== undefined) {
            console.log(!!window && window.matchMedia('(prefers-color-scheme: dark)'))
            setF(() => window.open)
        }
    }, [])
    const [f, setF] = useState()
    return (
        <div className={styles.container}>
            <Head>
                <title>React Demo </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Tooltip title="Material UI">
                <a
                    style={{ display: 'block', textAlign: 'center' }}
                    // href="https://mui.com/material-ui/react-autocomplete/"
                    onClick={() => {
                        f('https://mui.com/material-ui/react-autocomplete/')
                    }}
                >
                    <img src="./192x192.png" alt="Material UI" width="200" height="200"></img>
                </a>
            </Tooltip>
            <footer className={styles.footer}>
                <a href="#" target="_blank" rel="noopener noreferrer">
                    @footer
                </a>
            </footer>
        </div>
    )
}
